### ISSUE TITLE
✨ Coursemology Integration Phase 1 Stage 1

### ISSUE THREAD

**Issue by huyuxin0429** [WING-NUS/SSID#308]
Cc:

Hi
  
### Pain

Currently we do not have a clear idea of what the API specifications for coursemology looks like. Ensuring that the specification is more concrete will help to clarify functional requirements of the API.

See [https://github.com/WING-NUS/SSID/milestone/3](https://github.com/WING-NUS/SSID/milestone/3) for integration masterplan.

### Tasks

Ensure the following fields are contained in our API specification:
- [ ] POST API key to be submitted in header.
- [ ] POST API body to include field for submissions: zip file that contains all submitted files and template data (structure to be confirmed)
- [ ] POST API body to include field for references: zip file that contains all past course files.
- [ ] POST API body to include optional parameters: detection threshold, n-gram size etc
- [ ] GET API key to be submitted in header.
- [ ] GET API response body documentation.

Ensure the relevant response documentation are available:
- [ ] Document POST API responses:
Response for Error states (500 Generic Error, 503 Service Unavailable (When SSID is in maintenance mode), etc)
- [ ] Document GET API responses and body
- [ ] Common API specification sheet to be created and shared between SSID and Coursemology team. (Google Doc?)

### Acceptance Criteria

When all of the above fields are specificed in the API documentation.
When all of the above documentation are specified.

### More Information

Tentative deadline: 10/09/2023

### Screenshots

Thanks!
