### ISSUE TITLE
✨ Add sample mapping file for users to reference

### ISSUE THREAD

**Issue by huyuxin0429** [WING-NUS/SSID#313]
Cc:

Hi 
  
### Pain

Currently users might not have an idea of what a mapping file should look like. Providing an example mapping file will help clarify the usage of the file.

### Suggested Solution

Create sample mapping file for reference for users and display it on the upload page

### Tasks

- [ ] Create sample mapping file
- [ ] Add to upload page
- [ ] Update guidance information and documentation if needed

### Acceptance Criteria

Sample file provided in upload page. Clear instructions on how it is used. Should be unambiguous in terms of how its used.

### Screenshots

Thanks!
