### ISSUE TITLE
✨ SSID update misc tasks

### ISSUE THREAD

**Issue by huyuxin0429** [WING-NUS/SSID#322]
Cc:

Hi 
  
### Pain

@knmnyn Would like to update SSID's webpage.

### Tasks

- [ ] Sync master to production and dev server
- [ ] Update about page for SSID
- [ ] Upload SSID video

### Screenshots

Thanks!

**Comment by huyuxin0429** [comment]
Broken tasks down into subtasks
