### ISSUE TITLE
✨ Coursemology Integration Phase 1 Stage 2

### ISSUE THREAD

**Issue by sibinhho99** [WING-NUS/SSID#324]
Cc:

Hi 
  
### Pain

We want to implement SSID API so that users can programmatically use a subset of SSID's functionalities. This allows integration between Coursemology and SSID.

See [https://github.com/WING-NUS/SSID/milestone/3](https://github.com/WING-NUS/SSID/milestone/3) for integration masterplan.

### Suggested Solution

Implementing phase 1 of SSID API according to [https://github.com/WING-NUS/SSID/issues/308](https://github.com/WING-NUS/SSID/issues/308)

### Tasks

- [ ] API key authentication 
- [ ] `POST /api/v1/courses/{course_id}/assignment/` for creating new assignment 
- [ ] `GET /api/v1/assignments/{assignment_id}/submission_similarities/` for retrieving all submission similarities of an assignment
- [ ] `GET /api/v1/assignments/{assignment_id}/submission_similarities/{submission_similarities_id}` for retrieving details of a pair of a flagged submissions
- [ ] Modify frontend for additional params
- [ ] Create documentation for the above
- [ ] RSpec tests for the above

### Acceptance Criteria

API functional as per [https://github.com/WING-NUS/SSID/issues/308](https://github.com/WING-NUS/SSID/issues/308)

### More Information

Tentative deadline: 24/09/2023

### Screenshots

Thanks!
