### ISSUE TITLE
✨Reupload SSID introduction video into site

### ISSUE THREAD

**Issue by huyuxin0429** [WING-NUS/SSID#333]
Cc:

Hi 
  
### Pain

Currently, SSID's video is linked to a youtube account which has since gone private. Users are now unable to view an introductionary video for SSID.

### Suggested Solution

Host SSID's video in the production server.

### Tasks

- [ ] Download SSID's introduction video from panotoop
- [ ] Upload SSID's video to production
- [ ] Ensure video is viewable

### Acceptance Criteria

Acceptable once SSID's video can be publically viewable.

### Screenshots

Thanks!
