### ISSUE TITLE
✨Feedback from user survey:

### ISSUE THREAD

**Issue by joeyylow** [WING-NUS/SSID#388]
Cc:

Hi 
  
### Pain

The restrictive input format requirements cause users to be frustrated when trying to submit complex, multi-part coding assignments. Users face issues when the codes have many parts (eg. many internal text files). These parts will not be able to be checked until all the lines are combined into a single, clean submission. This makes it difficult to process projects that contain many separate code files. The checker only works with a specific folder structure and file extensions.

### Suggested Solution

Allow users to submit complex, multi-part coding assignments seamlessly by enhancing the code submission process. Enable the checker to handle projects with multiple separate code files, accommodating diverse folder structures and file extensions.

### Tasks

- [ ] Research and implement ways that allow uploading and checking assignments with multiple code files.
- [ ] Think about the various file types that should be supported by the system.
- [ ] Implement a flexible folder structure and file extension recognition in the checker to adapt to various project setups.

### Acceptance Criteria

Users should be able to upload coding assignments with multiple code files.
The system should be able to process and evaluate assignments consisting of various file types and folder structures.

### Screenshots

Thanks!

**Comment by sibinhho99** [comment]
> > Currently multiple files belonging to the same student in the same folder (e.g. multiple java files each with a class) are concatenated together internally.
> > For example, for this submission zip: [cs1101_a1.zip](https://github.com/WING-NUS/SSID/files/13635476/cs1101_a1.zip)
> > All source files of student 01 (2 java files) are concatenated into a single file for processing
> > <img alt="image" width="762" src="https://private-user-images.githubusercontent.com/29513997/289538469-7522b9bb-4671-4843-866e-cc568546429a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNDc4NTEsIm5iZiI6MTcwMjM0NzU1MSwicGF0aCI6Ii8yOTUxMzk5Ny8yODk1Mzg0NjktNzUyMmI5YmItNDY3MS00ODQzLTg2NmUtY2M1Njg1NDY0MjlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDAyMTkxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2Zjg5OTRmZmRhZWI0ODRmMjA4MTlmMGU4ZGU4YTIzNDUzNjJkNzUwZThhYTQ1OWI4ZTgzMjhiY2UyZTk0ZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nvT2_DFsHjZooBxbZA9uw5w2eQym8kUN7D4wsV0TSAQ">
> 
> This concatenation is only for multiple files in the first level of the students' root folders (e.g. `01/Main.java`, `01/Tree.java`). Looks like there are some stale efforts to account for other types of structures: #144, #137

My bad, this information is incorrect. Currently recursively nested files are already accounted for (all of them would be combined into a single file for comparison)
<img width="809" alt="SCR-20240118-ioni" src="https://github.com/WING-NUS/SSID/assets/29513997/75aad715-6f40-48c8-9499-7a3dceab0499">
